# .github/workflows/deploy-cloudrun.yml
name: Deploy to Cloud Run and update agent_card

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: esm-spectral-assessor
      REGION: us-central1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build container and push to GCR
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          echo "Building image $IMAGE"
          gcloud builds submit --tag "$IMAGE" .

      - name: Deploy to Cloud Run
        id: deploy
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          echo "Deploying $IMAGE to Cloud Run service $SERVICE_NAME"
          gcloud run deploy "${{ env.SERVICE_NAME }}" \
            --image "$IMAGE" \
            --region "${{ env.REGION }}" \
            --platform managed \
            --allow-unauthenticated \
            --quiet
          SERVICE_URL=$(gcloud run services describe "${{ env.SERVICE_NAME }}" --region "${{ env.REGION }}" --format='value(status.url)')
          echo "SERVICE_URL=${SERVICE_URL}" >> $GITHUB_ENV
          echo "Deployed to $SERVICE_URL"

      - name: Update agent_card.toml and .well-known/agent-card.json
        env:
          SERVICE_URL: ${{ env.SERVICE_URL }}
        run: |
          python3 scripts/update_agent_card.py --url "${{ env.SERVICE_URL }}"

      - name: Create branch, commit updated agent_card and agent-card.json
        env:
          BRANCH: cloudrun-update-${{ github.sha }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git checkout -b "$BRANCH"
          git add agent_card.toml .well-known/agent-card.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(deploy): update agent_card entrypoint to Cloud Run URL"
            git push --set-upstream origin "$BRANCH"
          fi

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deploy): update agent_card entrypoint to Cloud Run URL"
          branch: cloudrun-update-${{ github.sha }}
          title: "Update agent_card entrypoint to Cloud Run URL"
          body: |
            This PR was opened automatically by the CI workflow. It updates `agent_card.toml`
            to point the `entrypoint` property to the freshly deployed Cloud Run service URL
            and writes `.well-known/agent-card.json`.
